import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/styles/globals.css";
import { AppProvider } from "@/shared/providers";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// 	fallback: ['system-ui', 'arial'],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// 	fallback: ['system-ui', 'arial'],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={` antialiased`}
			>
				<AppProvider>
					<div className="relative flex-col flex min-h-screen">
						<div className="h-screen w-full flex justify-center items-center px-10">
							{children}
						</div>
					</div>
				</AppProvider>
			</body>
		</html>
	);
}

// ${geistSans.variable} ${geistMono.variable}
